### ISSUE TITLE
Beamer colorlinks option

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#243]
If 'colorlinks' is true then the output with the Beamer template will give an error because linkcolor for hyperref is set to 'Maroon' on line 115 but that colour isn't defined. Adding 'dvipsnames' as a class option will fix this, I think. Is there any reason to think that this will break something else?

**Comment by jgm** [comment]
IN the latex template we have

    $if(colorlinks)$
    \PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
    $endif$

The one potential complication I see is that in beamer,
hyperref is loaded by the documentclass rather than by us.
I don't know if this would matter -- do you want to try
inserting the above into default.beamer and report back if
it works well?

+++ Thomas Hodgson [Feb 06 17 04:29 ]:

**Comment by twsh** [comment]
That didn't work for some reason. Adding this to the class did `$if(colorlinks)$dvipsnames,$endif$`.

**Comment by jgm** [comment]
Okay, great. That sounds fine. Do you want to submit a PR?

+++ Thomas Hodgson [Feb 06 17 06:07 ]:

**Comment by twsh** [comment]
Here it is: https://github.com/jgm/pandoc-templates/pull/244
