### ISSUE TITLE
Use polyglossia in beamer template

### ISSUE THREAD

**Issue by tindzk** [jgm/pandoc-templates#85]
When compiling with XeTeX, the beamer template should use ``polyglossia`` in lieu of ``babel``. For example:

```latex
\usepackage{polyglossia}
\setdefaultlanguage[spelling=new,babelshorthands=true]{german}
```

**Comment by nkalvi** [comment]
I'm not sure whether the default template needs to be updated, but have you looked at https://groups.google.com/forum/#!msg/pandoc-discuss/V3sPxP22Bis/KwSwou4lwBsJ?

> The easiest solution would be to add a `$spelling$` variable at the appropriate place in your LaTeX template, something like

>```pandoc-template
$if(german)$
\setmainlanguage[spelling=$if(spelling)$$spelling$$else$new$endif$$if(mainlang-opt)$,$for(mainlang-opt)$$mainlang-opt$$sep$,$endfor$$endif$]{german}
$else$
\setmainlanguage$if($mainlang-opt$[$for(mainlang-opt)$$mainlang-opt$$sep$,$endfor$]$endif${$if(mainlang)$$mainlang$$else$english$endif$}
$endif$
```

You get the general idea. I have several nested if-else clauses so that I can just write `swedish: 1`, `icelandic: 1`, `en-uk: 1` or `en-us: 1` in my metadata and have several options for both polyglossia and csquotes set appropriately for each of these languages, along with specific variables like `$swedish-quotes$` to override my own defaults.

**Comment by tindzk** [comment]
Thanks! I created a [pull request](https://github.com/jgm/pandoc-templates/pull/86) with a similar solution.

**Comment by nkalvi** [comment]
:+1:

**Comment by jgm** [comment]
To be conservative, I have just added the polyglossia code from the latex template.  I'm open to wider changes, but it would be good to have small pull requests that each do one thing.

**Comment by tindzk** [comment]
Thank you. I'd appreciate if you could also provide an option to use a different spelling. See https://github.com/tindzk/pandoc-templates/commit/072b91757d59b31eca5405983ed10414bb27738c.

**Comment by jgm** [comment]
Why don't you submit a separate issue or PR just for this spelling
issue.

+++ Tim Nieradzik [May 27 15 11:41 ]:
